export const mainTheme = {
  token: {
    fontFamily: "Poppins, sans-serif",
  },
  components: {
    Button: {
      colorPrimary: "#fff",
    },
    Menu: {
      colorPrimary: "#fff",
      iconSize: 24,
      fontSize: 18,
      itemActiveBg: "#fff",
      itemActiveColor: "#fff",
      itemHoverColor: "#ffffff",
      itemColor: "#262621",
      itemSelectedBg: "#0C2752",
      itemSelectedColor: "#fff",
      iconColor: "#fff",
      subMenuItemBg: "#fff",
    },
    Form: {
      colorError: "#e53935",
    },
    Checkbox: {
      colorPrimary: "#fff",
      colorPrimaryHover: "#fff",
    },
    Select: {
      colorTextQuaternary: "#535763",
      colorBgContainer: "rgba(0,0,0,0)",
      fontSize: 18,
      optionSelectedColor: "#535763",
      optionSelectedBg: "#fff",
      optionActiveBg: "#fff",
      optionActiveColor: "#535763",
      colorBorder: "#535763 ",
      colorBgElevated: "#EFEFEF",
      selectorBg: "#EFEFEF",
      colorText: "#535763",
      colorTextPlaceholder: "#fff",
      hoverBorderColor: "#fff",
      colorIcon: "#535763",
    },
    DatePicker: {
      fontSize: 20,
      colorTextPlaceholder: "#535763",
      colorBgElevated: "#0C2752",
      colorText: "#fff",
      colorTextHeading: "#fff",
      colorTextDisabled: "#535763",
      colorIcon: "#fff",
      colorIconHover: "#000",
      colorPrimary: "#000",
    },
    timePicker: {
      fontSize: 20,
      colorTextPlaceholder: "#D0D5DD",
      colorBgElevated: "#FADACD",
      colorText: "#fff",
      colorTextHeading: "#fffBB",
      colorTextDisabled: "#fff33",
      colorIcon: "#fff99",
      colorIconHover: "#fff",
      colorPrimary: "rgb(27,27,27)",
    },
    Upload: {
      colorTextQuaternary: "#000",
      colorFillAlter: "rgba(0,0,0,0)",
      colorBorder: "#fff",
      colorBorderHover: "#fff",
      colorText: "#000",
      colorIcon: "#000",
      actionsColor: "rgba(255,0,0)",
    },
    Table: {
      colorPrimary: "#fff",
      headerBg: "#0C2752",
      colorBgContainer: "#ffffff",
      colorText: "#0C2752",
      colorIcon: "#ffffff",
      borderColor: "#E1E1E1",
      headerColor: "#FFFFFF",
      fontSize: 18,
      footerColor: "#FDFDFD",
      // marginXXS: 4,
      colorLinkActive: "#FDFDFD",
      headerSplitColor: "#0C2752",

      headerSortActiveBg: "#fff",
      headerSortHoverBg: "#fff",
    },
    Pagination: {
      colorBgContainer: "#FFFFFF",
      itemActiveBg: "#28314e",
      itemActiveColor: "rgb(255,255,255)",
      colorPrimary: "#fff",
      colorPrimaryHover: "#fff",
      colorText: "#28314e",
      colorBgTextHover: "#28314e55",
    },
    Input: {
      colorTextPlaceholder: "#535763",
      colorIcon: "#535763",
      colorError: "#e53935",
    },
    Radio: {
      colorPrimary: "#fff",
      colorPrimaryHover: "#fff",
    },
    Modal: {
      contentBg: "#FFFFFF",
      headerBg: "#FFFFFF",
      colorIcon: "#000",
      colorIconHover: "#000",
    },
    Rate: {
      starBg: "#fff",
    },
    Collapse: {
      headerBg: "#fff",
    },
  },
};
