export const fieldOfficerData = [
    {
        key: "1",
        fullName: "John Doe",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        phoneNumber: "+8801234567890",
        email: "john.doe@example.com",
        date: "2025-07-20",
        collected_amount: "5,000",
    },
    {
        key: "2",
        fullName: "Emily Smith",
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        phoneNumber: "+8801987654321",
        email: "emily.smith@example.com",
        date: "2025-07-19",
        collected_amount: "3,200",
    },
    {
        key: "3",
        fullName: "Michael Johnson",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        phoneNumber: "+8801712345678",
        email: "michael.j@example.com",
        date: "2025-07-18",
        collected_amount: "4,500",
    },
    {
        key: "4",
        fullName: "Sophia Brown",
        image: "https://randomuser.me/api/portraits/women/4.jpg",
        phoneNumber: "+8801555555555",
        email: "sophia.brown@example.com",
        date: "2025-07-17",
        collected_amount: "2,800",
    },
    {
        key: "5",
        fullName: "David Wilson",
        image: "https://randomuser.me/api/portraits/men/5.jpg",
        phoneNumber: "+8801876543210",
        email: "david.w@example.com",
        date: "2025-07-16",
        collected_amount: "6,700",
    },
    {
        key: "6",
        fullName: "Olivia Davis",
        image: "https://randomuser.me/api/portraits/women/6.jpg",
        phoneNumber: "+8801934567890",
        email: "olivia.davis@example.com",
        date: "2025-07-15",
        collected_amount: "3,900",
    },
    {
        key: "7",
        fullName: "Daniel Martinez",
        image: "https://randomuser.me/api/portraits/men/7.jpg",
        phoneNumber: "+8801444444444",
        email: "daniel.m@example.com",
        date: "2025-07-14",
        collected_amount: "5,300",
    },
    {
        key: "8",
        fullName: "Ava Garcia",
        image: "https://randomuser.me/api/portraits/women/8.jpg",
        phoneNumber: "+8801788888888",
        email: "ava.garcia@example.com",
        date: "2025-07-13",
        collected_amount: "4,000",
    },
    {
        key: "9",
        fullName: "James Anderson",
        image: "https://randomuser.me/api/portraits/men/9.jpg",
        phoneNumber: "+8801765432109",
        email: "james.anderson@example.com",
        date: "2025-07-12",
        collected_amount: "2,500",
    },
    {
        key: "10",
        fullName: "Isabella Lee",
        image: "https://randomuser.me/api/portraits/women/10.jpg",
        phoneNumber: "+8801122334455",
        email: "isabella.lee@example.com",
        date: "2025-07-11",
        collected_amount: "6,200",
    },
];
