export const fieldOfficerData = [
    {
        key: "1",
        fullName: "John Doe",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        phoneNumber: "+8801234567890",
        email: "john.doe@example.com",
        date: "2025-07-20",
        collected_amount: "5,000",
        address: "Dhaka, Bangladesh"

    },
    {
        key: "2",
        fullName: "Emily Smith",
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        phoneNumber: "+8801987654321",
        email: "emily.smith@example.com",
        date: "2025-07-19",
        collected_amount: "3,200",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "3",
        fullName: "Michael Johnson",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        phoneNumber: "+8801712345678",
        email: "michael.j@example.com",
        date: "2025-07-18",
        collected_amount: "4,500",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "4",
        fullName: "Sophia Brown",
        image: "https://randomuser.me/api/portraits/women/4.jpg",
        phoneNumber: "+8801555555555",
        email: "sophia.brown@example.com",
        date: "2025-07-17",
        collected_amount: "2,800",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "5",
        fullName: "David Wilson",
        image: "https://randomuser.me/api/portraits/men/5.jpg",
        phoneNumber: "+8801876543210",
        email: "david.w@example.com",
        date: "2025-07-16",
        collected_amount: "6,700",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "6",
        fullName: "Olivia Davis",
        image: "https://randomuser.me/api/portraits/women/6.jpg",
        phoneNumber: "+8801934567890",
        email: "olivia.davis@example.com",
        date: "2025-07-15",
        collected_amount: "3,900",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "7",
        fullName: "Daniel Martinez",
        image: "https://randomuser.me/api/portraits/men/7.jpg",
        phoneNumber: "+8801444444444",
        email: "daniel.m@example.com",
        date: "2025-07-14",
        collected_amount: "5,300",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "8",
        fullName: "Ava Garcia",
        image: "https://randomuser.me/api/portraits/women/8.jpg",
        phoneNumber: "+8801788888888",
        email: "ava.garcia@example.com",
        date: "2025-07-13",
        collected_amount: "4,000",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "9",
        fullName: "James Anderson",
        image: "https://randomuser.me/api/portraits/men/9.jpg",
        phoneNumber: "+8801765432109",
        email: "james.anderson@example.com",
        date: "2025-07-12",
        collected_amount: "2,500",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "10",
        fullName: "Isabella Lee",
        image: "https://randomuser.me/api/portraits/women/10.jpg",
        phoneNumber: "+8801122334455",
        email: "isabella.lee@example.com",
        date: "2025-07-11",
        collected_amount: "6,200",
        address: "Dhaka, Bangladesh"
    },
];


export const leadsData = [
    {
        key: "1",
        fullName: "John Doe",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        phoneNumber: "+8801234567890",
        email: "john.doe@example.com",
        address: "Dhaka, Bangladesh"

    },
    {
        key: "2",
        fullName: "Emily Smith",
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        phoneNumber: "+8801987654321",
        email: "emily.smith@example.com",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "3",
        fullName: "Michael Johnson",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        phoneNumber: "+8801712345678",
        email: "michael.j@example.com",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "4",
        fullName: "Sophia Brown",
        image: "https://randomuser.me/api/portraits/women/4.jpg",
        phoneNumber: "+8801555555555",
        email: "sophia.brown@example.com",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "5",
        fullName: "David Wilson",
        image: "https://randomuser.me/api/portraits/men/5.jpg",
        phoneNumber: "+8801876543210",
        email: "david.w@example.com",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "6",
        fullName: "Olivia Davis",
        image: "https://randomuser.me/api/portraits/women/6.jpg",
        phoneNumber: "+8801934567890",
        email: "olivia.davis@example.com",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "7",
        fullName: "Daniel Martinez",
        image: "https://randomuser.me/api/portraits/men/7.jpg",
        phoneNumber: "+8801444444444",
        email: "daniel.m@example.com",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "8",
        fullName: "Ava Garcia",
        image: "https://randomuser.me/api/portraits/women/8.jpg",
        phoneNumber: "+8801788888888",
        email: "ava.garcia@example.com",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "9",
        fullName: "James Anderson",
        image: "https://randomuser.me/api/portraits/men/9.jpg",
        phoneNumber: "+8801765432109",
        email: "james.anderson@example.com",
        address: "Dhaka, Bangladesh"
    },
    {
        key: "10",
        fullName: "Isabella Lee",
        image: "https://randomuser.me/api/portraits/women/10.jpg",
        phoneNumber: "+8801122334455",
        email: "isabella.lee@example.com",
        address: "Dhaka, Bangladesh"
    },
];

export const applicationData = [
    {
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        key: "1",
        fullName: "Tanvir Ahmed Santo",
        phoneNumber: "01600000000",
        email: "abc@gmail.com",
        address: "New York, NY 10003, USA",
        purposeOfFinancing: "Business",
        typeOfFinancing: "Murabaha Business",
        loanAmountRequested: "$50,000",
        employmentStatus: "Employed",
        location: "Dhaka",
        monthlyIncome: "$5,000",
        preferredContact: "01600000000",
        term: "Yearly",
        nid: "0000 000 000",
        startDate: "20.20.2025",
        endDate: "20.20.2026",
        status: "pending"
    },
    {
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        key: "1",
        fullName: "Tanvir Ahmed Santo",
        phoneNumber: "01600000000",
        email: "abc@gmail.com",
        address: "New York, NY 10003, USA",
        purposeOfFinancing: "Business",
        typeOfFinancing: "Murabaha Business",
        loanAmountRequested: "$50,000",
        employmentStatus: "Employed",
        location: "Dhaka",
        monthlyIncome: "$5,000",
        preferredContact: "01600000000",
        term: "Yearly",
        nid: "0000 000 000",
        startDate: "20.20.2025",
        endDate: "20.20.2026",
        status: "rejected"
    },
    {
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        key: "1",
        fullName: "Tanvir Ahmed Santo",
        phoneNumber: "01600000000",
        email: "abc@gmail.com",
        address: "New York, NY 10003, USA",
        purposeOfFinancing: "Business",
        typeOfFinancing: "Murabaha Business",
        loanAmountRequested: "$50,000",
        employmentStatus: "Employed",
        location: "Dhaka",
        monthlyIncome: "$5,000",
        preferredContact: "01600000000",
        term: "Yearly",
        nid: "0000 000 000",
        startDate: "20.20.2025",
        endDate: "20.20.2026",
        status: "approved"
    },
    {
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        key: "1",
        fullName: "Tanvir Ahmed Santo",
        phoneNumber: "01600000000",
        email: "abc@gmail.com",
        address: "New York, NY 10003, USA",
        purposeOfFinancing: "Business",
        typeOfFinancing: "Murabaha Business",
        loanAmountRequested: "$50,000",
        employmentStatus: "Employed",
        location: "Dhaka",
        monthlyIncome: "$5,000",
        preferredContact: "01600000000",
        term: "Yearly",
        nid: "0000 000 000",
        startDate: "20.20.2025",
        endDate: "20.20.2026",
        status: "approved"
    },
    {
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        key: "1",
        fullName: "Tanvir Ahmed Santo",
        phoneNumber: "01600000000",
        email: "abc@gmail.com",
        address: "New York, NY 10003, USA",
        purposeOfFinancing: "Business",
        typeOfFinancing: "Murabaha Business",
        loanAmountRequested: "$50,000",
        employmentStatus: "Employed",
        location: "Dhaka",
        monthlyIncome: "$5,000",
        preferredContact: "01600000000",
        term: "Yearly",
        nid: "0000 000 000",
        startDate: "20.20.2025",
        endDate: "20.20.2026",
        status: "approved"
    },
    {
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        key: "1",
        fullName: "Tanvir Ahmed Santo",
        phoneNumber: "01600000000",
        email: "abc@gmail.com",
        address: "New York, NY 10003, USA",
        purposeOfFinancing: "Business",
        typeOfFinancing: "Murabaha Business",
        loanAmountRequested: "$50,000",
        employmentStatus: "Employed",
        location: "Dhaka",
        monthlyIncome: "$5,000",
        preferredContact: "01600000000",
        term: "Yearly",
        nid: "0000 000 000",
        startDate: "20.20.2025",
        endDate: "20.20.2026",
        status: "approved"
    },
    {
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        key: "1",
        fullName: "Tanvir Ahmed Santo",
        phoneNumber: "01600000000",
        email: "abc@gmail.com",
        address: "New York, NY 10003, USA",
        purposeOfFinancing: "Business",
        typeOfFinancing: "Murabaha Business",
        loanAmountRequested: "$50,000",
        employmentStatus: "Employed",
        location: "Dhaka",
        monthlyIncome: "$5,000",
        preferredContact: "01600000000",
        term: "Yearly",
        nid: "0000 000 000",
        startDate: "20.20.2025",
        endDate: "20.20.2026",
        status: "approved"
    },
    {
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        key: "1",
        fullName: "Tanvir Ahmed Santo",
        phoneNumber: "01600000000",
        email: "abc@gmail.com",
        address: "New York, NY 10003, USA",
        purposeOfFinancing: "Business",
        typeOfFinancing: "Murabaha Business",
        loanAmountRequested: "$50,000",
        employmentStatus: "Employed",
        location: "Dhaka",
        monthlyIncome: "$5,000",
        preferredContact: "01600000000",
        term: "Yearly",
        nid: "0000 000 000",
        startDate: "20.20.2025",
        endDate: "20.20.2026",
        status: "approved"
    },
    {
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        key: "1",
        fullName: "Tanvir Ahmed Santo",
        phoneNumber: "01600000000",
        email: "abc@gmail.com",
        address: "New York, NY 10003, USA",
        purposeOfFinancing: "Business",
        typeOfFinancing: "Murabaha Business",
        loanAmountRequested: "$50,000",
        employmentStatus: "Employed",
        location: "Dhaka",
        monthlyIncome: "$5,000",
        preferredContact: "01600000000",
        term: "Yearly",
        nid: "0000 000 000",
        startDate: "20.20.2025",
        endDate: "20.20.2026",
        status: "approved"
    },
    {
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        key: "1",
        fullName: "Tanvir Ahmed Santo",
        phoneNumber: "01600000000",
        email: "abc@gmail.com",
        address: "New York, NY 10003, USA",
        purposeOfFinancing: "Business",
        typeOfFinancing: "Murabaha Business",
        loanAmountRequested: "$50,000",
        employmentStatus: "Employed",
        location: "Dhaka",
        monthlyIncome: "$5,000",
        preferredContact: "01600000000",
        term: "Yearly",
        nid: "0000 000 000",
        startDate: "20.20.2025",
        endDate: "20.20.2026",
        status: "approved"
    },
];

export const loanData = [
    {
        title: "Type of Financing Request",
        _id: "1212",
        features: [
            "Cost plus profit (CPP) Murabaha Personal",
            "Cost plus profit (CPP) Murabaha Business",
            "Thrive Together Partnership (TTP) Mudaraba"
        ],
        isActive: true
    },
    {
        title: "Purpose of Financing",
        _id: "1212dd",
        features: [
            "Business Expansion",
            "Medical Expenses",
            "Home Renovation",
            "Education Support"
        ],
        isActive: true
    },
    {
        title: "Employment Status Options",
        _id: "1212df",
        features: [
            "Employed",
            "Self-Employed",
            "Unemployed",
            "Freelancer"
        ],
        isActive: false
    },
    {
        title: "Preferred Contact Methods",
        _id: "1212r6",
        features: [
            "Phone Call",
            "SMS",
            "Email",
            "WhatsApp"
        ],
        isActive: false
    },
    {
        title: "Repayment Term Options",
        _id: "1212po",
        features: [
            "Monthly",
            "Quarterly",
            "Yearly",
            "One-Time Payment"
        ],
        isActive: true
    }
];

export const installmentData = [
    {
        fullName: "Ariana Gomez",
        phoneNumber: "+1 202-555-0141",
        email: "ariana.gomez@example.com",
        city: "Los Angeles",
        loanAmount: "$2,500",
        term: "12 months",
        image: "https://randomuser.me/api/portraits/women/44.jpg",
        installmentAmount: "$250",
        dueDate: "2025-08-10",
        paidOn: "2025-08-08",
        penalty: "$0",
        status: "paid",
    },
    {
        fullName: "Michael Trent",
        phoneNumber: "+1 202-555-0175",
        email: "michael.trent@example.com",
        city: "Chicago",
        loanAmount: "$5,000",
        term: "10 months",
        image: "https://randomuser.me/api/portraits/men/32.jpg",
        installmentAmount: "$500",
        dueDate: "2025-07-01",
        paidOn: "2025-07-05",
        penalty: "$15",
        status: "late",
    },
    {
        fullName: "Emily Roberts",
        phoneNumber: "+1 202-555-0113",
        email: "emily.roberts@example.com",
        city: "San Diego",
        loanAmount: "$3,000",
        term: "10 months",
        image: "https://randomuser.me/api/portraits/women/58.jpg",
        installmentAmount: "$300",
        dueDate: "2025-07-20",
        paidOn: "2025-07-20",
        penalty: "$0",
        status: "paid",
    },
    {
        fullName: "Nathan Park",
        phoneNumber: "+1 202-555-0160",
        email: "nathan.park@example.com",
        city: "Seattle",
        loanAmount: "$4,500",
        term: "10 months",
        image: "https://randomuser.me/api/portraits/men/71.jpg",
        installmentAmount: "$450",
        dueDate: "2025-07-15",
        paidOn: "2025-07-17",
        penalty: "$10",
        status: "late",
    },
    {
        fullName: "Isla Benson",
        phoneNumber: "+1 202-555-0192",
        email: "isla.benson@example.com",
        city: "Houston",
        loanAmount: "$6,000",
        term: "10 months",
        image: "https://randomuser.me/api/portraits/women/25.jpg",
        installmentAmount: "$600",
        dueDate: "2025-07-22",
        paidOn: "",
        penalty: "$30",
        status: "overdue ",
    },
    {
        fullName: "Liam Anderson",
        phoneNumber: "+1 202-555-0129",
        email: "liam.anderson@example.com",
        city: "Phoenix",
        loanAmount: "$5,500",
        term: "10 months",
        image: "https://randomuser.me/api/portraits/men/10.jpg",
        installmentAmount: "$550",
        dueDate: "2025-07-12",
        paidOn: "2025-07-13",
        penalty: "$5",
        status: "late",
    },
    {
        fullName: "Sophia Lee",
        phoneNumber: "+1 202-555-0183",
        email: "sophia.lee@example.com",
        city: "Boston",
        loanAmount: "$3,500",
        term: "10 months",
        image: "https://randomuser.me/api/portraits/women/11.jpg",
        installmentAmount: "$350",
        dueDate: "2025-07-24",
        paidOn: "2025-07-24",
        penalty: "$0",
        status: "paid",
    },
    {
        fullName: "Ethan Moore",
        phoneNumber: "+1 202-555-0108",
        email: "ethan.moore@example.com",
        city: "Denver",
        loanAmount: "$4,200",
        term: "10 months",
        image: "https://randomuser.me/api/portraits/men/49.jpg",
        installmentAmount: "$420",
        dueDate: "2025-07-05",
        paidOn: "",
        penalty: "$25",
        status: "overdue ",
    },
    {
        fullName: "Grace Thompson",
        phoneNumber: "+1 202-555-0135",
        email: "grace.thompson@example.com",
        city: "Miami",
        loanAmount: "$3,000",
        term: "10 months",
        image: "https://randomuser.me/api/portraits/women/30.jpg",
        installmentAmount: "$300",
        dueDate: "2025-07-10",
        paidOn: "2025-07-09",
        penalty: "$0",
        status: "paid",
    },
    {
        fullName: "Noah Carter",
        phoneNumber: "+1 202-555-0148",
        email: "noah.carter@example.com",
        city: "Austin",
        loanAmount: "$4,750",
        term: "10 months",
        image: "https://randomuser.me/api/portraits/men/28.jpg",
        installmentAmount: "$475",
        dueDate: "2025-07-14",
        paidOn: "",
        penalty: "$20",
        status: "overdue ",
    },
];


export const officerData = [
    {
        key: "1",
        foId: "FO001",
        fullName: "John Doe",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        phoneNumber: "+8801234567890",
        email: "john.doe@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-11-10",
        nid: "1234567890123",
        hubId: "HUB-DHK-01",
        setLocation: "23.8103, 90.4125",
        cv: "https://example.com/cv/john_doe.pdf",
    },
    {
        key: "2",
        foId: "FO002",
        fullName: "Emily Smith",
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        phoneNumber: "+8801987654321",
        email: "emily.smith@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-09-15",
        nid: "2234567890123",
        hubId: "HUB-DHK-02",
        setLocation: "23.7800, 90.4000",
        cv: "https://example.com/cv/emily_smith.pdf",
    },
    {
        key: "3",
        foId: "FO003",
        fullName: "Michael Johnson",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        phoneNumber: "+8801712345678",
        email: "michael.j@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-08-01",
        nid: "3234567890123",
        hubId: "HUB-DHK-03",
        setLocation: "23.8200, 90.4150",
        cv: "https://example.com/cv/michael_johnson.pdf",
    },
    {
        key: "4",
        foId: "FO004",
        fullName: "Sophia Brown",
        image: "https://randomuser.me/api/portraits/women/4.jpg",
        phoneNumber: "+8801555555555",
        email: "sophia.brown@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-07-20",
        nid: "4234567890123",
        hubId: "HUB-DHK-04",
        setLocation: "23.7750, 90.3900",
        cv: "https://example.com/cv/sophia_brown.pdf",
    },
    {
        key: "5",
        foId: "FO005",
        fullName: "David Wilson",
        image: "https://randomuser.me/api/portraits/men/5.jpg",
        phoneNumber: "+8801876543210",
        email: "david.w@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-06-10",
        nid: "5234567890123",
        hubId: "HUB-DHK-05",
        setLocation: "23.7900, 90.4050",
        cv: "https://example.com/cv/david_wilson.pdf",
    },
    {
        key: "6",
        foId: "FO006",
        fullName: "Olivia Davis",
        image: "https://randomuser.me/api/portraits/women/6.jpg",
        phoneNumber: "+8801934567890",
        email: "olivia.davis@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-05-05",
        nid: "6234567890123",
        hubId: "HUB-DHK-06",
        setLocation: "23.7650, 90.3850",
        cv: "https://example.com/cv/olivia_davis.pdf",
    },
    {
        key: "7",
        foId: "FO007",
        fullName: "Daniel Martinez",
        image: "https://randomuser.me/api/portraits/men/7.jpg",
        phoneNumber: "+8801444444444",
        email: "daniel.m@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-04-12",
        nid: "7234567890123",
        hubId: "HUB-DHK-07",
        setLocation: "23.8000, 90.4200",
        cv: "https://example.com/cv/daniel_martinez.pdf",
    },
    {
        key: "8",
        foId: "FO008",
        fullName: "Ava Garcia",
        image: "https://randomuser.me/api/portraits/women/8.jpg",
        phoneNumber: "+8801788888888",
        email: "ava.garcia@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-03-10",
        nid: "8234567890123",
        hubId: "HUB-DHK-08",
        setLocation: "23.7700, 90.3950",
        cv: "https://example.com/cv/ava_garcia.pdf",
    },
    {
        key: "9",
        foId: "FO009",
        fullName: "James Anderson",
        image: "https://randomuser.me/api/portraits/men/9.jpg",
        phoneNumber: "+8801765432109",
        email: "james.anderson@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-02-18",
        nid: "9234567890123",
        hubId: "HUB-DHK-09",
        setLocation: "23.8300, 90.4100",
        cv: "https://example.com/cv/james_anderson.pdf",
    },
    {
        key: "10",
        foId: "FO010",
        fullName: "Isabella Lee",
        image: "https://randomuser.me/api/portraits/women/10.jpg",
        phoneNumber: "+8801122334455",
        email: "isabella.lee@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-01-22",
        nid: "1034567890123",
        hubId: "HUB-DHK-10",
        setLocation: "23.7850, 90.4070",
        cv: "https://example.com/cv/isabella_lee.pdf",
    },
];

export const spokeManagerFieldOfficerData = [
    {
        key: "1",
        foId: "SM001",
        fullName: "John Doe",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        phoneNumber: "+8801234567890",
        email: "john.doe@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-11-10",
        nid: "1234567890123",
        hubId: "HUB-DHK-01",
        setLocation: "23.8103, 90.4125",
        cv: "https://example.com/cv/john_doe.pdf",
    },
    {
        key: "2",
        foId: "SM002",
        fullName: "Jane Smith",
        image: "https://randomuser.me/api/portraits/women/2.jpg",
        phoneNumber: "+8809876543210",
        email: "jane.smith@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-10-15",
        nid: "2234567890123",
        hubId: "HUB-DHK-02",
        setLocation: "23.8150, 90.4150",
        cv: "https://example.com/cv/jane_smith.pdf",
    },
    {
        key: "3",
        foId: "SM003",
        fullName: "Michael Johnson",
        image: "https://randomuser.me/api/portraits/men/3.jpg",
        phoneNumber: "+8809876543210",
        email: "michael.j@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-09-20",
        nid: "3234567890123",
        hubId: "HUB-DHK-03",
        setLocation: "23.8150, 90.4150",
        cv: "https://example.com/cv/michael_johnson.pdf",
    },
    {
        key: "4",
        foId: "SM004",
        fullName: "Emily Davis",
        image: "https://randomuser.me/api/portraits/women/4.jpg",
        phoneNumber: "+8809876543210",
        email: "emily.davis@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-08-25",
        nid: "4234567890123",
        hubId: "HUB-DHK-04",
        setLocation: "23.8150, 90.4150",
        cv: "https://example.com/cv/emily_davis.pdf",
    },
    {
        key: "5",
        foId: "SM005",
        fullName: "David Wilson",
        image: "https://randomuser.me/api/portraits/men/5.jpg",
        phoneNumber: "+8809876543210",
        email: "david.w@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-07-30",
        nid: "5234567890123",
        hubId: "HUB-DHK-05",
        setLocation: "23.8150, 90.4150",
        cv: "https://example.com/cv/david_wilson.pdf",
    },
    {
        key: "6",
        foId: "SM006",
        fullName: "Sophia Brown",
        image: "https://randomuser.me/api/portraits/women/6.jpg",
        phoneNumber: "+8809876543210",
        email: "sophia.brown@example.com",
        address: "Dhaka, Bangladesh",
        date: "2023-07-30",
        nid: "6234567890123",
        hubId: "HUB-DHK-06",
        setLocation: "23.8150, 90.4150",
        cv: "https://example.com/cv/sophia_brown.pdf",
    },
];